version: '3.4'

services:
  app:
    container_name: startiv-classroom
    image: startiv-classroom
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /bin/sh -c "npm run start:prod && npx wait-on http://localhost:5000"
    ports:
      - 5000:5000
      - 5001:5001
    restart: always
    environment:
      - NODE_ENV=local
      - JWT_SECRET=someJwtStrongPassword
      - PORT=5000
      - DB_USERNAME=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD=supersecretpassword
      - DB_NAME=classroom
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_DB=0
      - MEDIA_HOST=http://127.0.0.1:5001
    depends_on:
      - db
      - cache
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=classroom
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - 5433:5432 # for loggin in and creating admin
    volumes:
      - ./db:/var/lib/postgresql/data
  cache:
    image: redis:latest
